language: node_js
node_js:
- '0.10'
addons:
  sauce_connect: true
env:
  global:
  - secure: qkjAyle8KMB6BaHAWwFvgckEgsylmwWY4iM24HsFoRtG2tFT9knoSbysp0BYEF1BTsyDMUHVE9Hvf66BzqMgz0L7rDzrz+n1MRe5Z/i3G4ksjubJGBaf0F8pNguaHpjmbMldtxw4Pv+QwY9RfGc6f6zG840Unrt51xGUYEmviOE=
  - secure: cSa6qHoVwiV6HyJ6e5Fy5QFQ9Vj9Jn30pxfat4kU+t7d8aoCU/Nsxokxt3ZX2Ef8xf0gIbZkt5Lva2XavWy0czJBWg9OFdh4Sf0uJsswGNQ8CmlAlCTEQexWOKH6Yxsl4iK3l6S8l4rqWDdBkLIHlgT4bfgTqHGOQxp2f9zcq+A=
  - secure: M1nY/CpAX0GFXfgDUy3wT4ZGAnacPslvEpnscgS8shz4CFD0Ri7u67TRAmMVz39n/5C0Zs0u7es902g29ykL/eNZvIdK2A/J+rp+aFCNuUzMHtu0VR3TwUTSrxt4760RZ2OHz9IS7Ba6PxnHQ63I1ryhd7DnwmiKEIyADqLdJPE=
  - secure: L9F+hlFZXNNSkSQN4/MfY+P6/Zgo7BaWq4EleTweZRR+Y6oH0A0vlJipeP/GbOnsBxRSJVMv+sCMFwKdDvIB5YlhKDQNhF+Jkl3dAytfTQ/Wnb+9TKhPzqi3g+8Z0HU1eVPTyo2Ra2KIC6rb3+0+ednWX+Smt+uwdY9jnZ799MI=
before_script:
- npm install -g bower
- bower install
- npm install -g grunt-cli
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- grunt
