language: node_js
node_js:
- '0.11'
env:
  global:
  - secure: JjP7KN5VfGxzpPQTk0Qh+5axkJN8Tcoenu5vNvZTocH3MhH3/jOUvV3cu+e09F6Uat90WLciqs8JhGELAzfmHBnMMHSbLjMucD4XNhJNv5nVc86FrWEeJZUSBnPu08qmPZLacaRlIEdHsK4G0rZTAidsuUGNAfdSdfe8yWNHRTA=
  - secure: ACzjKTIglg+W5I0Jhgf4n2RtUKTGth9Hkle9iTpt952ctXvB0BbsfoNVqFdQkYhPGhjsb3iJZwu5iFCzAXjmbS572/RMiuIb59UUpgGuSgxBylmfgRndb5uxGB6zwXWlcSJzdITv9Aj8y9iemT+2HtkAnYbNR4r0hICJlo/fyEo=
addons:
  sauce_connect: true
before_script:
- npm install -g bower
- bower install
- npm install -g grunt-cli
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- grunt travis
