language: node_js
node_js:
- '0.10'
addons:
  firefox: '31.0'
install:
- npm config set spin false
- npm config set loglevel http
- time npm install
- time npm install -g grunt-cli bower
- time bower install
before_script:
- if [ -n "$LOGS_DIR" ]; then mkdir -p $LOGS_DIR; fi
- if [ -n "$BROWSER_PROVIDER_READY_FILE" ]; then ./scripts/sauce_connect_setup.sh;
  fi
- if [ -n "$BROWSER_PROVIDER_READY_FILE" ]; then ./scripts/wait_for_browser_provider.sh;
  fi
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: grunt $GRUNT_TASK
after_success: grunt deploy
matrix:
  fast_finish: true
  allow_failures:
  - env: GRUNT_TASK=saucelabs-tests BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready LOGS_DIR=/tmp/nolap-report-editor-build/logs
env:
  matrix:
  - GRUNT_TASK=tests
  - GRUNT_TASK=saucelabs-tests BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready LOGS_DIR=/tmp/nolap-report-editor-build/logs
  global:
  - secure: YqbQT5/kfhFkcjKek8HD0FklGTa9/TwCXul1p6G+xS3gTNRdlWW2TvOglhlvUNTJeVSNT/vGZs/IsbTunxs3mk8ztDUMZVUfnlkJoRJLL0I6vLyBMnr+UnJhuwiBOB7583Lichi1wCn7SVFCamH0EscatqySO1F9xBEx1GDnA9I=
  - secure: Q/x0pr+/P/BB+kUfMWqI1NOyETCEoarFB2RtVQTd3B0zRo4oyjUQ+vCzEl2UUvErn+jOJ9suZxQ1usKKZOCe5u4Mi2rmdJJjpgrNYdbmcqwdSVMEcqEx0urYFz5eu1ZmFmM5XYsim0WLdjfLzlDJzlB0uyteurtHPwIbc9x9W1M=
  - secure: HgQbwQth2+xvoQ9LaE94SqH6XZ/NwBxW+wLxtJZHnbURRQPIZTNpWTw8A9L+3yymsMFYxievt9rFqNzwEep74qc994WnUKz23zEglUuzFdq9IULaCaVZwryAnEhe5QzGTaFzfxeYA/zPNfCZMLg1a4mkFIVTlzdKP181rmcLn/c=
  - secure: CNa8pS2/HuRa4yHIMjq43yPNOkJGz5K2q8JNAAxs31sLlj6iYY7fPcmjogOCo6ZuXxPAwMEUGTiewl3dyHFGqVvcc4MN680TjouxoXQ4C62oBzrS++Rh1E05EE6a50O4EwxaETIwEJUJJsY9fFb+GYi2+BRM4olI4rSLfYQtq7s=
